version: '3.8'

# Production environment override

networks:
  default:
    internal: true
  public:
    external: ${TRAEFIK_ENABLE:-false}
    name: ${TRAEFIK_NETWORK:-~}

services:
  php:
    build:
      context: .
      target: frankenphp_prod
    networks:
      - default
      - public
    labels:
      - traefik.docker.network=${TRAEFIK_NETWORK:-~}
      - traefik.enable=${TRAEFIK_ENABLE:-false}
      - traefik.http.routers.yazoo-php.entrypoints=http
      - traefik.http.routers.yazoo-php.rule=Host(`${APP_HOSTNAME:-localhost}`)
      - traefik.http.services.yazoo-php.loadbalancer.server.port=80
    env_file: stack.env

  db:
    image: mariadb:${MARIADB_VERSION:-10.8.38}
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    env_file: stack.env

volumes:
  db_data: {}
