version: "3.4"

# Production environment override
services:
  php:
    build:
      context: .
      target: frankenphp_prod
    ports: []
    environment:
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}?serverVersion=mariadb-10.3.38&charset=utf8mb4

  db:
    image: mariadb:10.3.38
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: {}
