version: "3.8"

services:
  php:
    restart: unless-stopped
    image: ${IMAGE_NAME-yazoo:latest}
    depends_on:
      - db
    build:
      context: .
      target: frankenphp_dev
    volumes:
      - ./:/app
      - ./frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./frankenphp/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
      - caddy_data:/data
      - caddy_config:/config
    env_file:
      - etc/defaults.env

  db:
    image: mariadb:${MARIADB_VERSION:-10.3.38}
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./etc/yazoo.sql:/docker-entrypoint-initdb.d/00_yazoo.sql
    env_file:
      - etc/defaults.env


volumes:
  caddy_data:
  caddy_config:
  mariadb-data: