version: "3.8"

services:
  php:
    restart: unless-stopped
    image: ${IMAGE_NAME-yazoo:latest}
    depends_on:
      - db
    build:
      context: .
      target: frankenphp_dev
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    env_file:
      - etc/defaults.env

volumes:
  caddy_data:
  caddy_config:
