version: "3.4"

# Production environment override
networks:
  default:
    internal: true
  public:
    external: true
    name: net-pastis-hosting-docker_public

services:
  php:
    build:
      context: .
      target: frankenphp_prod
    environment:
      APP_ENV: prod
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}?serverVersion=mariadb-10.3.38&charset=utf8mb4
    networks:
      - default
      - net-pastis-hosting-docker_public
    labels:
      - traefik.docker.network=net-pastis-hosting-docker_public
      - traefik.enable=true
      - traefik.http.routers.yazoo-php.entrypoints=http
      - traefik.http.routers.yazoo-php.rule=Host(`yazoo.constructions-incongrues.net`)

  db:
    image: mariadb:10.3.38
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: {}
