version: '3.8'

services:
  php:
    build:
      context: .
      target: frankenphp_dev
    volumes:
      - ../../:/workspaces
    depends_on:
      - db

  db:
    image: mariadb:10.3.38
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: yazoo
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp
        
    # Add "forwardPorts": ["3306"] to **devcontainer.json** to forward MariaDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  mariadb-data:
