name: CI

on:
  push:
    branches:
      - main
  pull_request: ~
  workflow_dispatch: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build Docker images
        uses: docker/bake-action@v4
        with:
          pull: true
          load: true
          files: |
            compose.yaml
            compose.override.yaml
            .devcontainer/compose.override.yaml
          set: |
            *.cache-from=type=gha,scope=${{github.ref}}
            *.cache-from=type=gha,scope=refs/heads/main
            *.cache-to=type=gha,scope=${{github.ref}},mode=max
      -
        name: Start services
        run: |
          docker compose -f compose.yaml -f compose.override.yaml -f .devcontainer/compose.override.yaml up --wait --no-build db
          sleep 15
          docker compose -f compose.yaml -f compose.override.yaml -f .devcontainer/compose.override.yaml up --wait --no-build php
      -
        name: Check HTTP reachability
        run: curl -v http://localhost
      -
        name: Check HTTPS reachability
        run: curl -vk https://localhost
      -
        name: Doctrine Schema Validator
        run: docker compose exec -T php bin/console doctrine:schema:validate
